# Emits internal/softdelete/relations_gen.go: the reverse-relation graph
# plane.bgtasks.deletion_task.soft_delete_related_objects walks. Run inside
# the reference container:
#   docker compose -f docker-compose.dev.yml exec -T reference python manage.py shell \
#     < contract/reference/gen_cascade.py | sed -n '/^\/\/ Code generated/,$p' > internal/softdelete/relations_gen.go
from django.apps import apps

# soft_delete_related_objects reads CASCADE children through their `objects`
# manager and SET_NULL children through the default manager. Where that
# manager filters beyond deleted_at, the rows it hides are skipped; these are
# the equivalent SQL conditions on the child table. A manager missing here
# fails generation.
MANAGER_FILTERS = {
    ("states", "objects"): """"group" <> 'triage'""",
    ("issues", "issue_objects"): (
        "archived_at IS NULL AND NOT is_draft"
        " AND NOT EXISTS (SELECT 1 FROM states s WHERE s.id = issues.state_id AND s.\"group\" = 'triage')"
        " AND NOT EXISTS (SELECT 1 FROM projects p WHERE p.id = issues.project_id AND p.archived_at IS NOT NULL)"
    ),
}


def manager_filter(model, manager):
    where = str(manager.all().query).split(" WHERE ", 1)
    plain = '"%s"."deleted_at" IS NULL' % model._meta.db_table
    if len(where) == 1 or where[1].split(" ORDER BY ")[0] == plain:
        return ""
    key = (model._meta.db_table, manager.name)
    if key not in MANAGER_FILTERS:
        raise SystemExit("no SQL for manager %s.%s: %s" % (key + (where[1],)))
    return MANAGER_FILTERS[key]


rows = []
for m in apps.get_models():
    if m._meta.app_label not in ("db", "license") or m._meta.proxy:
        continue
    if not any(f.name == "deleted_at" for f in m._meta.concrete_fields):
        continue
    for f in m._meta.get_fields():
        if not ((f.one_to_many or f.one_to_one) and f.auto_created and not f.concrete):
            continue
        on_delete = getattr(f.on_delete, "__name__", "")
        if on_delete == "DO_NOTHING":
            continue
        child = f.related_model
        soft = any(x.name == "deleted_at" for x in child._meta.concrete_fields)
        if on_delete != "SET_NULL" and not soft:
            continue  # cascade into a model without deleted_at is a no-op
        manager = child._default_manager if on_delete == "SET_NULL" else getattr(child, "objects", child._default_manager)
        rows.append((m._meta.db_table, child._meta.db_table, f.remote_field.column, on_delete == "SET_NULL", soft,
                     manager_filter(child, manager) if soft else ""))

print("// Code generated by contract/reference/gen_cascade.py; DO NOT EDIT.")
print()
print("package softdelete")
print()
print("// relations lists, for every soft-deletable table, the reverse foreign keys")
print("// soft_delete_related_objects follows: {parent, child, child column,")
print("// SET_NULL, child is soft-deletable, extra filter of the child's manager}.")
print("var relations = []relation{")
for r in sorted(rows):
    print('\t{"%s", "%s", "%s", %s, %s, %s},' % (r[0], r[1], r[2], str(r[3]).lower(), str(r[4]).lower(),
                                            "`%s`" % r[5] if r[5] else '""'))
print("}")
