# Emits ALTER TABLE ... SET DEFAULT statements reproducing Django model
# defaults at the database level, so Go INSERTs can omit columns exactly like
# the ORM fills them. Run inside the reference container:
#   python manage.py shell < gen_defaults.py
import json, uuid, decimal, datetime, sys
from django.apps import apps
from django.db import connection
from django.utils import timezone

def lit(f, v):
    if v is None:
        return "NULL"
    it = f.get_internal_type()
    if it == "JSONField":
        return "'%s'::jsonb" % json.dumps(v).replace("'", "''")
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float, decimal.Decimal)):
        return repr(v) if not isinstance(v, decimal.Decimal) else str(v)
    if isinstance(v, uuid.UUID):
        return "'%s'::uuid" % v
    if isinstance(v, (datetime.datetime, datetime.date)):
        return "'%s'" % v.isoformat()
    if isinstance(v, str):
        return "'%s'" % v.replace("'", "''")
    if isinstance(v, (list, tuple)) and it == "ArrayField":
        return "'{%s}'" % ",".join('"%s"' % x for x in v)
    raise TypeError(f"unsupported default {v!r} for {f}")

out, skipped = [], []
for m in apps.get_models():
    if m._meta.app_label not in ("db", "license") or m._meta.proxy or not m._meta.managed:
        continue
    t = m._meta.db_table
    for f in m._meta.local_concrete_fields:
        col = f.column
        if getattr(f, "auto_now_add", False) or getattr(f, "auto_now", False):
            out.append(f'ALTER TABLE "{t}" ALTER COLUMN "{col}" SET DEFAULT now();')
            continue
        if not f.has_default():
            # Django's implicit default for non-null text columns is "".
            if not f.null and f.empty_strings_allowed and f.get_internal_type() in (
                "CharField", "TextField", "SlugField", "EmailField", "URLField",
            ) and not f.primary_key:
                out.append(f"ALTER TABLE \"{t}\" ALTER COLUMN \"{col}\" SET DEFAULT '';")
            continue
        d = f.default
        if callable(d):
            if d is uuid.uuid4:
                out.append(f'ALTER TABLE "{t}" ALTER COLUMN "{col}" SET DEFAULT gen_random_uuid();')
                continue
            if d is timezone.now:
                out.append(f'ALTER TABLE "{t}" ALTER COLUMN "{col}" SET DEFAULT now();')
                continue
            a, b = d(), d()
            if a != b:
                skipped.append(f"{t}.{col}: non-deterministic default {getattr(d, '__qualname__', d)}")
                continue
            v = a
        else:
            v = d
        try:
            out.append(f'ALTER TABLE "{t}" ALTER COLUMN "{col}" SET DEFAULT {lit(f, v)};')
        except TypeError as e:
            skipped.append(f"{t}.{col}: {e}")

print("-- Django model defaults reproduced at the database level (generated by")
print("-- contract/reference/gen_defaults.py). Lets Go INSERTs omit columns the ORM")
print("-- would fill. Non-deterministic defaults are handled in Go instead:")
for s in skipped:
    print("--   " + s)
print()
for line in sorted(out):
    print(line)
