# Emits internal/harddelete/relations_gen.go: the relation graph Django's
# deletion Collector walks when plane.bgtasks.deletion_task.hard_delete calls
# Model.all_objects.filter(...).delete(), and the models its final loop
# sweeps. Run inside the reference container:
#   scripts/devstack.sh N shell < contract/reference/gen_hard_delete.py \
#     | sed -n '/^\/\/ Code generated/,$p' | gofmt > internal/harddelete/relations_gen.go
from django.apps import apps
from django.db import connection

rows = []
pks = {}


def pk_of(model):
    pk = model._meta.pk
    return pk.column, pk.db_type(connection)


# The Collector follows every reverse one-to-many/one-to-one relation,
# hidden ones included (auto-created many-to-many tables), and reads the
# children through their _base_manager (a plain Manager: soft-deleted rows
# too).
for m in apps.get_models(include_auto_created=True):
    if m._meta.proxy:
        continue
    for f in m._meta.get_fields(include_hidden=True):
        if not ((f.one_to_many or f.one_to_one) and f.auto_created and not f.concrete):
            continue
        child = f.related_model
        if child._meta.proxy:
            continue
        on_delete = f.on_delete.__name__
        if on_delete not in ("CASCADE", "SET_NULL", "DO_NOTHING"):
            raise SystemExit("unsupported on_delete %s on %s.%s" % (on_delete, child._meta.db_table, f.field.column))
        if f.field.target_field != m._meta.pk:
            raise SystemExit("foreign key to a non-pk column: %s.%s" % (child._meta.db_table, f.field.column))
        if child._base_manager.__class__.__name__ != "Manager":
            raise SystemExit("custom base manager on %s" % child._meta.db_table)
        rows.append((m._meta.db_table, child._meta.db_table, f.field.column, on_delete))
        pks[m._meta.db_table] = pk_of(m)
        pks[child._meta.db_table] = pk_of(child)

# hard_delete's last loop: every model with a deleted_at attribute, in
# registry order.
swept = [m._meta.db_table for m in apps.get_models() if hasattr(m, "deleted_at")]
for m in apps.get_models():
    if hasattr(m, "deleted_at"):
        pks[m._meta.db_table] = pk_of(m)

kinds = {"CASCADE": "cascade", "SET_NULL": "setNull", "DO_NOTHING": "doNothing"}
print("// Code generated by contract/reference/gen_hard_delete.py; DO NOT EDIT.")
print()
print("package harddelete")
print()
print("// relations lists every reverse foreign key Django's deletion Collector")
print("// follows: {parent, child, child column, on_delete}.")
print("var relations = []relation{")
for r in sorted(rows):
    print('\t{"%s", "%s", "%s", %s},' % (r[0], r[1], r[2], kinds[r[3]]))
print("}")
print()
print("// pks gives each table's primary key column and SQL type.")
print("var pks = map[string][2]string{")
for t in sorted(pks):
    print('\t"%s": {"%s", "%s"},' % (t, pks[t][0], pks[t][1]))
print("}")
print()
print("// SoftDeletable lists the tables of the models with a deleted_at")
print("// attribute, in Django's app registry order (hard_delete's final loop).")
print("var SoftDeletable = []string{")
for t in swept:
    print('\t"%s",' % t)
print("}")
